public enum BrushStatus
{
    INTRO_MOVIE,
    PREPARE_PASTE,
    GREEN_MOLD_01,
    BRUSH_STANDBY, BRUSH_BUBBLE_EXPLOSION,
    BRUSH_GUIDE_01, BRUSH_AR_GUIDE_01, BRUSH_GUIDE_02, BRUSH_AR_GUIDE_02,
    BRUSH_GUIDE_03, BRUSH_AR_GUIDE_03, BRUSH_GUIDE_04, BRUSH_AR_GUIDE_04,
    GREEN_MOLD_02,
    BRUSH_GUIDE_05, BRUSH_AR_GUIDE_05, BRUSH_GUIDE_06, BRUSH_AR_GUIDE_06,
    BRUSH_GUIDE_07, BRUSH_AR_GUIDE_07, BRUSH_GUIDE_08, BRUSH_AR_GUIDE_08,
    GREEN_MOLD_03,
    BRUSH_GUIDE_09, BRUSH_AR_GUIDE_09, BRUSH_GUIDE_10, BRUSH_AR_GUIDE_10,
    BRUSH_GUIDE_11, BRUSH_AR_GUIDE_11, BRUSH_GUIDE_12, BRUSH_AR_GUIDE_12,
    GREEN_MOLD_04,
    BRUSH_GUIDE_13, BRUSH_AR_GUIDE_13, BRUSH_GUIDE_14, BRUSH_AR_GUIDE_14,
    BRUSH_GUIDE_15, BRUSH_AR_GUIDE_15, BRUSH_GUIDE_16, BRUSH_AR_GUIDE_16,
    // FINISH_TONGUE, FINISH_BRUSH, FINISH_CUP, FINISH_GARGLE, FINISH_WATER
    FINISH_TONGUE, FINISH_BRUSH, FINISH_WATER, FINISH_GARGLE, FINISH_CUP
}
